// src/components/parts/hero.tsx
import React from "react"
import PropTypes from "prop-types"

import styles from "./hero.module.css"

type Props = {
  isLarge?: boolean
  title?: React.ReactNode
  subTitle?: React.ReactNode
  body?: React.ReactNode
  background?: string
}

const HeroComponent: React.FC<Props> = props => {
  const wrapAttribute = {
    "data-large": props.isLarge ? "" : null,
  }

  let { title, subTitle, body, background } = props
  if (!background) {
    background = "/content/background.jpg"
  }

  return (
    <div className={styles.wrap} {...wrapAttribute}>
      <div className={styles.figure}>
        {background ? (
          <img
            src={background}
            className={styles.image}
            loading="lazy"
            alt={title ? title.toString() : ""}
          />
        ) : (
          ""
        )}
      </div>

      <div className={`l-container ${styles.inner}`}>
        {title ? <h1 className={styles.title}>{title}</h1> : ""}
        {subTitle ? <h2 className={styles.sub_title}>{subTitle}</h2> : ""}
        {body ? body : ""}
      </div>
    </div>
  )
}

HeroComponent.defaultProps = {
  isLarge: false,
  background: "/content/background.jpg",
}

HeroComponent.propTypes = {
  isLarge: PropTypes.bool,
  title: PropTypes.node,
  subTitle: PropTypes.node,
  body: PropTypes.node,
  background: PropTypes.string,
}

export default HeroComponent

// components/Parts/Hero.vue
<template lang="pug">
  .c-hero(:class="{'is-large': isLarge}")
    .c-hero__figure
      img(:src="image" loading="lazy" v-if="image").c-hero__image
      img(src="/content/background.jpg" loading="lazy" v-else).c-hero__image
    .l-container.c-hero__inner
      h1.c-hero__title(v-if="$scopedSlots.title")
        slot(name="title")
      h2.c-hero__sub-title(v-if="$scopedSlots.subTitle")
        slot(name="subTitle")

      slot
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  name: 'ComponentPartHero',
  props: {
    isLarge: { type: Boolean, default: false },
    image: { type: String, default: '' },
  },
})
</script>
